services:
  - type: web
    name: doc-translator-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "from app.main import start; start()"
    envVars:
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: CLOUDFLARE_ACCOUNT_ID
        sync: false
      - key: CLOUDFLARE_ACCESS_KEY_ID
        sync: false
      - key: CLOUDFLARE_ACCESS_KEY_SECRET
        sync: false
      - key: R2_BUCKET_NAME
        sync: false