name = "doc-translator-api"
main = "app/main.py"
compatibility_date = "2024-01-01"

[vars]
OPENAI_API_KEY = ""
CLOUDFLARE_ACCOUNT_ID = ""
CLOUDFLARE_ACCESS_KEY_ID = ""
CLOUDFLARE_ACCESS_KEY_SECRET = ""
R2_BUCKET_NAME = ""

[[r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = 'your-bucket-name'

[build]
command = "pip install -r requirements.txt"
